"""Restore sign_convention to financial_line_item

Revision ID: 705e17c2c225
Revises: 88c62cd5a6f6
Create Date: 2026-07-22 12:31:17.085699

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "705e17c2c225"
down_revision: Union[str, Sequence[str], None] = "88c62cd5a6f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Restore sign_convention and its check constraint.

    Both were dropped unintentionally by an autogenerated migration: the ORM
    attribute was missing while the database column existed, so Alembic read
    the difference as an instruction to drop.
    """
    op.add_column(
        "financial_line_item",
        sa.Column(
            "sign_convention",
            sa.String(length=16),
            nullable=False,
            server_default="as_printed",
        ),
    )
    op.create_check_constraint(
        "ck_sign_convention",
        "financial_line_item",
        "sign_convention IN ('as_printed', 'negated_label')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_sign_convention", "financial_line_item", type_="check")
    op.drop_column("financial_line_item", "sign_convention")
