"""Widen financial_line_item.value to numeric(18,4)

Revision ID: 88c62cd5a6f6
Revises: 08a7ccfba048
Create Date: 2026-07-22 12:07:10.354357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c62cd5a6f6'
down_revision: Union[str, Sequence[str], None] = '08a7ccfba048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_line_item', 'value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.drop_column('financial_line_item', 'sign_convention')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_line_item', sa.Column('sign_convention', sa.VARCHAR(length=16), server_default=sa.text("'as_printed'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('financial_line_item', 'value',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
