"""Initial schema: documents, periods, line items, metrics, targets, insights

Revision ID: ce2eee455f8c
Revises: 
Create Date: 2026-07-21 10:25:38.082080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2eee455f8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporting_period',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_audited', sa.Boolean(), nullable=False),
    sa.Column('reporting_entity', sa.String(length=64), nullable=False),
    sa.Column('reporting_basis', sa.String(length=16), nullable=False),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.CheckConstraint("period_type IN ('annual', 'half_year')", name='ck_period_type'),
    sa.CheckConstraint("reporting_basis IN ('company', 'group', 'mixed')", name='ck_period_basis'),
    sa.CheckConstraint("reporting_entity IN ('ADF Farm Solutions Limited', 'Senus PLC')", name='ck_period_entity'),
    sa.CheckConstraint('end_date > start_date', name='ck_period_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('source_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_ref', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('reporting_entity', sa.String(length=64), nullable=False),
    sa.Column('reporting_basis', sa.String(length=16), nullable=False),
    sa.CheckConstraint("document_type IN ('information_document', 'half_year_results', 'presentation', 'press_release')", name='ck_document_type'),
    sa.CheckConstraint("reporting_basis IN ('company', 'group', 'mixed')", name='ck_doc_basis'),
    sa.CheckConstraint("reporting_entity IN ('ADF Farm Solutions Limited', 'Senus PLC')", name='ck_doc_entity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_ref')
    )
    op.create_table('computed_metric',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=64), nullable=False),
    sa.Column('reporting_period_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('calculation_version', sa.String(length=16), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_derived_input', sa.Boolean(), nullable=False),
    sa.Column('caveat', sa.Text(), nullable=True),
    sa.CheckConstraint("unit IN ('eur', 'percent', 'ratio', 'months', 'count')", name='ck_metric_unit'),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_type', 'reporting_period_id', 'calculation_version', name='uq_metric_identity')
    )
    op.create_table('extraction_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('fixture_path', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('sample_checked', sa.Integer(), nullable=True),
    sa.Column('error_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('error_rate IS NULL OR (error_rate >= 0 AND error_rate <= 1)', name='ck_error_rate_range'),
    sa.CheckConstraint('sample_checked IS NULL OR sample_size IS NULL OR sample_checked <= sample_size', name='ck_sample_within_size'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insight',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('fixture_path', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporting_period_id', 'section', 'prompt_version', name='uq_insight')
    )
    op.create_table('segment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_id', sa.UUID(), nullable=False),
    sa.Column('segment_type', sa.String(length=16), nullable=False),
    sa.Column('segment_name', sa.String(length=64), nullable=False),
    sa.Column('revenue_share_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('revenue_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('avg_contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.CheckConstraint("segment_type IN ('channel', 'geography', 'product')", name='ck_segment_type'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_segment_confidence'),
    sa.CheckConstraint('revenue_share_pct IS NULL OR (revenue_share_pct >= 0 AND revenue_share_pct <= 100)', name='ck_segment_share_range'),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_period.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporting_period_id', 'segment_type', 'segment_name', name='uq_segment_identity')
    )
    op.create_table('target',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('target_period_label', sa.String(length=32), nullable=False),
    sa.Column('baseline_period_id', sa.UUID(), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.CheckConstraint("unit IN ('eur', 'percent', 'ratio', 'months', 'count')", name='ck_target_unit'),
    sa.ForeignKeyConstraint(['baseline_period_id'], ['reporting_period.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_period_label', name='uq_target_identity')
    )
    op.create_table('financial_line_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('statement', sa.String(length=32), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_location', sa.Text(), nullable=True),
    sa.Column('data_class', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_note', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("data_class IN ('statement', 'narrative', 'approximation')", name='ck_data_class'),
    sa.CheckConstraint("statement IN ('profit_and_loss', 'balance_sheet', 'cash_flow', 'narrative')", name='ck_statement'),
    sa.CheckConstraint("validation_status IN ('valid', 'flagged', 'failed')", name='ck_validation_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_confidence_range'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_period.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', 'reporting_period_id', 'label', name='uq_line_item_identity')
    )
    op.create_table('metric_line_item_link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('computed_metric_id', sa.UUID(), nullable=False),
    sa.Column('financial_line_item_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.CheckConstraint("role IN ('numerator', 'denominator', 'prior_period', 'current_period', 'component')", name='ck_link_role'),
    sa.ForeignKeyConstraint(['computed_metric_id'], ['computed_metric.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_line_item_id'], ['financial_line_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('computed_metric_id', 'financial_line_item_id', 'role', name='uq_link_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_line_item_link')
    op.drop_table('financial_line_item')
    op.drop_table('target')
    op.drop_table('segment')
    op.drop_table('insight')
    op.drop_table('extraction_run')
    op.drop_table('computed_metric')
    op.drop_table('source_document')
    op.drop_table('reporting_period')
    # ### end Alembic commands ###
